### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by 44011406** [ading2210/edpuzzle-answers#5]
Everytime i press the button "Asnwer Questions or Skip Video" it doesnt work. Also it doesnt shows the underlines, what happened? 

![Screenshot 2023-01-20 3 38 17 PM](https://user-images.githubusercontent.com/123180419/213801077-eb24b605-08cf-4372-a46c-2104f01ac3b3.png)

**Comment by ading2210** [comment]
It's been fixed now, just clear your cache. jsDelivr, which is used to load the main script, has a significantly longer cache duration than Github, which is used to load all the other files. Moving most of the JS files to a separate directory broke all the older versions that were still cached by the browser, since those would have still been referencing the old paths.
